// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FilmDB))]
    [Migration("20220316161433_Add_Yonetmen")]
    partial class Add_Yonetmen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Afis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Altyazili")
                        .HasColumnType("bit");

                    b.Property<string>("FilmAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Ozet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sure")
                        .HasColumnType("int");

                    b.Property<int>("YonetmenID")
                        .HasColumnType("int");

                    b.HasKey("FilmID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("YonetmenID");

                    b.ToTable("Filmler");

                    b.HasData(
                        new
                        {
                            FilmID = 1,
                            Afis = "ij_1.jpg",
                            Altyazili = false,
                            FilmAdi = "Indiana Jones",
                            KategoriID = 1,
                            Sure = 95,
                            YonetmenID = 1
                        },
                        new
                        {
                            FilmID = 2,
                            Afis = "av.jpg",
                            Altyazili = true,
                            FilmAdi = "Ace Ventura",
                            KategoriID = 3,
                            Sure = 98,
                            YonetmenID = 2
                        },
                        new
                        {
                            FilmID = 3,
                            Afis = "fury.jpg",
                            Altyazili = false,
                            FilmAdi = "Fury",
                            KategoriID = 2,
                            Sure = 106,
                            YonetmenID = 1
                        },
                        new
                        {
                            FilmID = 4,
                            Afis = "bf.jpg",
                            Altyazili = true,
                            FilmAdi = "Bebek Firarda",
                            KategoriID = 3,
                            Sure = 103,
                            YonetmenID = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriID");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAdi = "Macera"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAdi = "Savaş"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAdi = "Komedi"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Yonetmen", b =>
                {
                    b.Property<int>("YonetmenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YonetmenAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YonetmenID");

                    b.ToTable("Yonetmenler");

                    b.HasData(
                        new
                        {
                            YonetmenID = 1,
                            YonetmenAdi = "Tarantino"
                        },
                        new
                        {
                            YonetmenID = 2,
                            YonetmenAdi = "Mel Gibson"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Film", b =>
                {
                    b.HasOne("WebApplication1.Models.Kategori", "Kategori")
                        .WithMany("Filmler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Yonetmen", "Yonetmen")
                        .WithMany("Filmler")
                        .HasForeignKey("YonetmenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Yonetmen");
                });

            modelBuilder.Entity("WebApplication1.Models.Kategori", b =>
                {
                    b.Navigation("Filmler");
                });

            modelBuilder.Entity("WebApplication1.Models.Yonetmen", b =>
                {
                    b.Navigation("Filmler");
                });
#pragma warning restore 612, 618
        }
    }
}
